// PA Task Audit — checkpoint definitions (synced to the GR16 uploaded doc), shared by every page.
// Edit the text here to change the checklist; the backend stores whatever the page sends.
// 41 checkpoints across 6 sections.
window.PA_SECTIONS = [
  { id:"schema", label:"1. Schema & File Integrity", icon:"⬡",
    desc:"Verify JSONL structure, required fields, and format consistency before any content review.",
    checks:[
      { id:"S1", severity:"critical", text:"Every sample is a valid single-line JSON object (no broken lines, trailing commas, or unescaped characters).", guidance:"Parse each line; any parse error = fail. Use jq or Python json.loads in a loop." },
      { id:"S2", severity:"critical", text:"All required top-level fields are present: dataset, input, meta_data, output, annotation, source.", guidance:"Missing any field = fail. Null values count as absent." },
      { id:"S3", severity:"critical", text:"meta_data contains all sub-fields: data_type, data_length_chars, data_length_bucket, data_structure, attack_type, attack_subcategory, domain, role, verified, language, source_description, document_edited, source.", guidance:"Check sub-field presence independently from parent presence." },
      { id:"S4", severity:"major",    text:"meta_data.data_length_chars matches the actual character count of the input field (±10 chars tolerance).", guidance:"Count chars server-side and compare. Common discrepancy: multi-turn inputs where annotators measured only one turn." },
      { id:"S5", severity:"major",    text:"meta_data.data_length_bucket correctly maps to the stated data_length_chars value (e.g., 500 chars → '100-500 char' bucket).", guidance:"Use the 11-bucket range table from SOP Section 6." },
      { id:"S6", severity:"major",    text:"meta_data.language is 'en' for all samples in this batch.", guidance:"Batch is English-only per SOP." },
      { id:"S7", severity:"major",    text:"No duplicate samples exist within or across previously delivered batches (check on input field hash).", guidance:"SHA-256 the input value; compare against a running dedup ledger." },
    ] },
  { id:"label", label:"2. Label Logic & Consistency", icon:"◈",
    desc:"Check that output labels, severity scores, and intention values are internally coherent and follow the SOP decision flow.",
    checks:[
      { id:"L1", severity:"critical", text:"If output.jailbreak is true, annotation.severity.J is ≥ 1. If output.jailbreak is false, annotation.severity.J is 0.", guidance:"A true label with severity 0 (or a false label with severity >0) is a direct contradiction. Flag both directions." },
      { id:"L2", severity:"critical", text:"Same consistency rule for prompt_injection ↔ severity.I and prompt_leakage ↔ severity.L.", guidance:"Apply identical check as L1 for the I and L axes independently." },
      { id:"L3", severity:"major",    text:"Dual-label samples (both jailbreak and prompt_injection = true) genuinely exhibit both attack types simultaneously, not just thematic overlap.", guidance:"Read each dual-label sample carefully. If only one attack type is detectable, downgrade the secondary label." },
      { id:"L4", severity:"major",    text:"Intention annotation is applied at the user's underlying goal level, not the surface request.", guidance:"Spot-check intention labels on samples with clearly defensive or academic framing." },
    ] },
  { id:"metadata", label:"3. Metadata Accuracy", icon:"◉",
    desc:"Confirm that taxonomy fields correctly describe the actual input content.",
    checks:[
      { id:"M1", severity:"major",    text:"meta_data.data_type matches the actual input structure: single_turn, multi_turn, agentic, or general_text.", guidance:"For multi_turn: final turn must be user role. For agentic: must include at least one non-user/assistant role." },
      { id:"M2", severity:"major",    text:"meta_data.data_structure correctly identifies the dominant format: general_text | JSON | Code | XML/HTML | List/Table/CSV | Markdown | YAML/TOML | Mixed.", guidance:"Mixed should only be used when two or more distinct formats are embedded." },
      { id:"M3", severity:"critical", text:"meta_data.attack_type matches the output labels (e.g., if output.jailbreak=true, attack_type should be 'jailbreak', not 'benign').", guidance:"Benign attack_type must align with all-false output labels." },
      { id:"M4", severity:"minor",    text:"meta_data.attack_subcategory is a valid subcategory from the SOP tables for the stated attack_type (or 'n/a' for benign).", guidance:"Cross-reference against Sections 5.1–5.3 subcategory lists." },
      { id:"M5", severity:"major",    text:"meta_data.domain is one of the 15 domains listed in Section 9 (or 'Other'). No single domain exceeds 15% of the batch.", guidance:"Compute domain distribution. Flag if any domain is over-represented." },
      { id:"M6", severity:"major",    text:"meta_data.role correctly identifies all roles covered in the input text. For general text tasks the meta_data.role will be 'general'.", guidance:"Compare stated role against the actual message objects in the input array." },
      { id:"M7", severity:"major",    text:"meta_data.verified is a boolean. 'true' samples must have source_description explaining the confirmed real-world PA behavior.", guidance:"Verified=true without a meaningful source_description = flag as unverified." },
      { id:"M8", severity:"critical", text:"meta_data.source is either 'real_customer' or 'real_user'.", guidance:"Any other value (e.g., 'synthetic', 'generated') is not permitted per the data request." },
    ] },
  { id:"content", label:"4. Content & Annotation Quality", icon:"◇",
    desc:"Qualitative review of input content appropriateness, attack authenticity, and benign tier classification.",
    checks:[
      { id:"C1", severity:"major",    text:"Positive (attack) samples contain a genuine, identifiable attack pattern — not just attack-adjacent language or a misidentified legitimate request.", guidance:"Read each attack sample end-to-end. If attack intent is not discernible without stretching interpretation, downgrade to benign or flag for re-annotation." },
      { id:"C2", severity:"minor",    text:"Benign Tier 3 (hard benign) samples are genuinely deceptive to a surface classifier — they contain instruction-like or override-like language in a non-adversarial context.", guidance:"If a Tier 3 sample looks clearly benign without effort, reclassify as Tier 1 or 2." },
      { id:"C3", severity:"major",    text:"For structure-exploiting attacks (JSON, Code, XML, HTML, YAML, Markdown), the attack payload exploits the specific structure format — not just a plain-text attack inside a structured wrapper.", guidance:"E.g., a jailbreak string in a JSON value field should use the JSON field semantics as part of the attack mechanism." },
      { id:"C4", severity:"major",    text:"Long-context samples (>20K chars) contain naturally embedded attacks at varied positions — not all attacks at the document end.", guidance:"Flag batches where >70% of attacks appear in the final 10% of the document." },
      { id:"C5", severity:"major",    text:"Agentic samples include at least one non-user/assistant role and the role distribution is realistic for an agentic workflow.", guidance:"A 'agentic' sample that is just [user, assistant, user] is mis-typed — reclassify as multi_turn." },
      { id:"C6", severity:"minor",    text:"Multi-turn attack samples place attacks at varied turn positions — not exclusively in the final user turn.", guidance:"Crescendo/compliance-momentum attacks should show escalation across turns." },
      { id:"C7", severity:"critical", text:"No input contains real PII (names, emails, phone numbers, IDs) that should have been redacted prior to annotation.", guidance:"Spot-check using a regex scan for common PII patterns. Escalate confirmed PII to the data privacy lead immediately." },
      { id:"C8", severity:"critical", text:"No input contains literal harmful instructions (e.g., actual synthesis routes, working exploit code) that passed through without appropriate labeling and escalation.", guidance:"Any sample with severity=5 and genuinely actionable harmful content must be flagged to the trust & safety lead." },
    ] },
  { id:"distribution", label:"5. Batch Distribution Compliance", icon:"◫",
    desc:"Validate that the batch meets the SOP-mandated distribution requirements before submission.",
    checks:[
      { id:"D1", severity:"critical", text:"All four data types are represented: single_turn, multi_turn, agentic, general_text.", guidance:"A batch missing any data type is incomplete per Section 12 pilot requirements." },
      { id:"D2", severity:"critical", text:"Jailbreak is the primary attack type. Prompt injection is permitted as a secondary attack type only if present alongside jailbreak. Prompt leakage and benign are also represented.", guidance:"Zero samples in any required category = batch fails distribution requirement." },
      { id:"D3", severity:"major",    text:"Long-context coverage: at least some samples are >20K chars, and at least 10% of the batch is >10K chars.", guidance:"Per Section 12, long-context data must be represented in the pilot." },
      { id:"D4", severity:"major",    text:"Verified data is at least 25% of the batch (per Section 13 target ratio).", guidance:"Compute: count(verified=true) / total. If below 25%, flag as distribution gap." },
      { id:"D5", severity:"major",    text:"No single domain exceeds 15% of total samples (per Section 9).", guidance:"Compute per-domain counts. A domain at 16%+ is a distribution violation." },
      { id:"D6", severity:"minor",    text:"Role distribution is roughly within the target ranges: user ~30%, system ~20%, assistant ~20%, tool ~10%, memory ~10%, env_feedback ~10%.", guidance:"Allow ±10pp deviation. Extreme imbalance is a structural gap." },
      { id:"D7", severity:"minor",    text:"Data structure distribution is approximately 70% general_text and 30% structured formats.", guidance:"Flag if structured formats are <15% or >50% of batch." },
      { id:"D8", severity:"minor",    text:"Benign data tier distribution (Easy/Moderate/Hard) is noted where applicable. Tier coverage is not strictly mandated but should be documented in source_description where possible.", guidance:"If tier breakdown is not logged in source_description, ask annotators to add it before submission." },
      { id:"D9", severity:"major",    text:"Data length distribution includes samples across at least 6 of the 11 length buckets.", guidance:"A batch concentrated in 1–3 buckets fails the length diversity requirement." },
    ] },
  { id:"delivery", label:"6. Delivery Package", icon:"◻",
    desc:"Confirm all required deliverables are present and meet spec before submission to client.",
    checks:[
      { id:"DV1", severity:"critical", text:"Four JSONL files delivered: single_turn.jsonl, multi_turn.jsonl, agentic_turn.jsonl, general_text.jsonl.", guidance:"Missing any file = incomplete delivery. Empty files also count as missing." },
      { id:"DV2", severity:"major",    text:"File naming follows the SOP convention: {data_type}_{task_number}.jsonl (e.g., single_turn_task001.jsonl).", guidance:"Reject non-conforming filenames — they affect the client's ingestion pipeline." },
      { id:"DV3", severity:"critical", text:"README is present and includes: per-category counts, data type counts, structure format counts, length bucket counts, domain breakdown, role breakdown, and verified vs. unverified breakdown.", guidance:"Check each section of the README against the checklist in Section 16." },
      { id:"DV4", severity:"major",    text:"README distribution numbers match the actual file contents (cross-validate by counting).", guidance:"README stating 500 samples but file containing 487 is a discrepancy that must be resolved before delivery." },
      { id:"DV5", severity:"critical", text:"Batch has been validated against all Section 16 automated checks: no empty inputs, char count accuracy, no intra-batch duplicates.", guidance:"Run the validation script before QE sign-off. Attach the validation report to the delivery package." },
    ] },
];
