// PA Task Audit — checkpoint definitions (shared by every page).
// Edit the text here to change the checklist; the backend stores whatever the page sends.
window.PA_SECTIONS = [
  { id:"schema", label:"1. Schema & File Integrity", icon:"⬡",
    desc:"Verify JSONL structure, required fields, and format consistency before any content review.",
    checks:[
      { id:"s1",  severity:"critical", text:"Every sample is a valid single-line JSON object (no broken lines, trailing commas, or unescaped characters).", guidance:"Parse each line; any parse error = fail. Use jq or Python json.loads in a loop." },
      { id:"s2",  severity:"critical", text:"All required top-level fields are present: dataset, input, meta_data, output, annotation, source.", guidance:"Missing any field = fail. Null values count as absent." },
      { id:"s3",  severity:"critical", text:"meta_data contains all sub-fields: data_type, data_length_chars, data_length_bucket, data_structure, attack_type, attack_subcategory, domain, role, verified, language, source_description.", guidance:"Check sub-field presence independently from parent presence." },
      { id:"s4",  severity:"critical", text:"output object contains all three boolean fields: jailbreak, prompt_injection, prompt_leakage.", guidance:"All three must be present; value must be boolean true/false, not string." },
      { id:"s5",  severity:"critical", text:"annotation.severity contains J, I, L keys each with integer 0–5. annotation.intention is one of: benign | adversarial | hard_to_say.", guidance:"Out-of-range scores or misspelled intention values = fail." },
      { id:"s6",  severity:"critical", text:"input field is non-empty. For multi-turn/agentic types, input is a JSON array of role/content objects; for single-turn and general_text it is a plain string.", guidance:"Empty string or empty array = fail." },
      { id:"s7",  severity:"major",    text:"meta_data.data_length_chars matches the actual character count of the input field (±10 chars tolerance).", guidance:"Count chars server-side and compare. Common discrepancy source: multi-turn inputs where annotators measured only one turn." },
      { id:"s8",  severity:"major",    text:"meta_data.data_length_bucket correctly maps to the stated data_length_chars value (e.g., 500 chars → '100-500 char' bucket).", guidance:"Use the 11-bucket range table from the SOP Section 6." },
      { id:"s9",  severity:"major",    text:"meta_data.language is 'en' for all samples in this batch.", guidance:"Batch is English-only per SOP." },
      { id:"s10", severity:"major",    text:"No duplicate samples exist within or across previously delivered batches (check on input field hash).", guidance:"SHA-256 the input value; compare against a running dedup ledger." },
    ] },
  { id:"label", label:"2. Label Logic & Consistency", icon:"◈",
    desc:"Check that output labels, severity scores, and intention values are internally coherent and follow the SOP decision flow.",
    checks:[
      { id:"l1", severity:"critical", text:"If output.jailbreak is true, annotation.severity.J is ≥ 1. If output.jailbreak is false, annotation.severity.J is 0.", guidance:"A true label with severity 0 (or a false label with severity >0) is a direct contradiction. Flag both directions." },
      { id:"l2", severity:"critical", text:"Same consistency rule for prompt_injection ↔ severity.I and prompt_leakage ↔ severity.L.", guidance:"Apply identical check as l1 for the I and L axes independently." },
      { id:"l3", severity:"major",    text:"Samples with all three output labels false have severity J=0, I=0, L=0 and intention=benign (unless annotator flags hard_to_say with justification).", guidance:"A fully-benign output label paired with adversarial intention is logically inconsistent; flag for review." },
      { id:"l4", severity:"major",    text:"The annotator applied the Appendix A exemption correctly: samples coded as educational/defensive/academic are labeled benign (severity=0) even when surface text resembles an attack.", guidance:"Spot-check 10% of severity-0 samples that contain attack-adjacent language. Confirm exemption criteria genuinely apply." },
      { id:"l5", severity:"major",    text:"Dual-label samples (both jailbreak and prompt_injection = true) genuinely exhibit both attack types simultaneously in the input, not just thematic overlap.", guidance:"Read each dual-label sample carefully. If only one attack type is detectable, downgrade the secondary label." },
      { id:"l6", severity:"major",    text:"Severity boundary guidance is respected: score 3 requires a recognizable attack pattern; score 4 requires clear intentional sophistication; score 5 requires explicit, blatant attack with zero benign interpretation.", guidance:"Check every score-5 sample — if any benign reading is plausible, it is at most a 4." },
      { id:"l7", severity:"minor",    text:"Severity scores are differentiated appropriately across the 0–5 scale. Batch does not show excessive clustering (>50% of labelled samples at a single score).", guidance:"Compute distribution histogram. Clustering at 3 or 5 is a common pattern that indicates calibration drift." },
      { id:"l8", severity:"major",    text:"Intention annotation is applied at the user's underlying goal level, not the surface request. A security researcher asking about jailbreaks should be benign intention, not adversarial.", guidance:"Spot-check intention labels on samples with clearly defensive or academic framing." },
    ] },
  { id:"metadata", label:"3. Metadata Accuracy", icon:"◉",
    desc:"Confirm that taxonomy fields correctly describe the actual input content.",
    checks:[
      { id:"m1", severity:"major",    text:"meta_data.data_type matches the actual input structure: 'single_turn', 'multi_turn', 'agentic', 'general_text'.", guidance:"For multi_turn: final turn must be user role. For agentic: must include at least one non-user/assistant role." },
      { id:"m2", severity:"major",    text:"meta_data.data_structure correctly identifies the dominant format: general_text | JSON | Code | XML/HTML | List/Table/CSV | Markdown | YAML/TOML | Mixed.", guidance:"Mixed should only be used when two or more distinct formats are embedded." },
      { id:"m3", severity:"critical", text:"meta_data.attack_type matches the output labels (e.g., if output.jailbreak=true, attack_type should be 'jailbreak', not 'benign').", guidance:"Benign attack_type must align with all-false output labels." },
      { id:"m4", severity:"minor",    text:"meta_data.attack_subcategory is a valid subcategory from the SOP tables for the stated attack_type (or 'N/A' for benign).", guidance:"Cross-reference against Sections 5.1–5.3 subcategory lists. 'Any' is a valid value for novel attacks." },
      { id:"m5", severity:"major",    text:"meta_data.domain is one of the 15 domains listed in Section 9 (or 'Other'). No single domain exceeds 15% of the batch.", guidance:"Compute domain distribution. Flag if any domain is over-represented." },
      { id:"m6", severity:"major",    text:"meta_data.role correctly identifies the primary role of the input.", guidance:"Compare stated role against the actual message objects in the input array." },
      { id:"m7", severity:"major",    text:"meta_data.verified is a boolean. 'true' samples must have source_description explaining the confirmed real-world PA behavior.", guidance:"Verified=true without a meaningful source_description = flag as unverified." },
      { id:"m8", severity:"critical", text:"meta_data.source is either 'real_customer' or 'real_user'.", guidance:"Any other value (e.g., 'synthetic', 'generated') is not permitted per the data request." },
    ] },
  { id:"content", label:"4. Content & Annotation Quality", icon:"◇",
    desc:"Qualitative review of input content appropriateness, attack authenticity, and benign tier classification.",
    checks:[
      { id:"c1", severity:"major",    text:"Positive (attack) samples contain a genuine, identifiable attack pattern — not just attack-adjacent language or a misidentified legitimate request.", guidance:"Read each attack sample end-to-end. If the attack intent is not discernible without stretching interpretation, downgrade to benign or flag for re-annotation." },
      { id:"c2", severity:"minor",    text:"Benign Tier 3 (hard benign) samples are genuinely deceptive to a surface classifier — they contain instruction-like or override-like language in a non-adversarial context.", guidance:"If a Tier 3 sample looks clearly benign without any effort, it should be reclassified as Tier 1 or 2." },
      { id:"c3", severity:"major",    text:"For structure-exploiting attacks (JSON, Code, XML, HTML, YAML, Markdown), the attack payload exploits the specific structure format — not just a plain-text attack inside a structured wrapper.", guidance:"E.g., a jailbreak string in a JSON value field should use the JSON field semantics as part of the attack mechanism." },
      { id:"c4", severity:"major",    text:"Long-context samples (>20K chars) contain naturally embedded attacks at varied positions (beginning, middle, end) — not all attacks at the document end.", guidance:"For long attack samples, record the character position of the attack payload. Flag batches where >70% of attacks appear in the final 10% of the document." },
      { id:"c5", severity:"major",    text:"Agentic samples include at least one non-user/assistant role and the role distribution is realistic for an agentic workflow.", guidance:"A 'agentic' sample that is just [user, assistant, user] is mis-typed — reclassify as multi_turn." },
      { id:"c6", severity:"minor",    text:"Multi-turn attack samples place attacks at varied turn positions — not exclusively in the final user turn.", guidance:"Crescendo/compliance-momentum attacks should show escalation across turns." },
      { id:"c7", severity:"critical", text:"No input contains real PII (names, emails, phone numbers, IDs) that should have been redacted prior to annotation.", guidance:"Spot-check using a regex scan for common PII patterns. Escalate any confirmed PII to the data privacy lead immediately." },
      { id:"c8", severity:"critical", text:"No input contains literal harmful instructions (e.g., actual synthesis routes, working exploit code) that passed through without appropriate labeling and escalation.", guidance:"Any sample with severity=5 and genuinely actionable harmful content must be flagged to the trust & safety lead, not just labeled." },
    ] },
  { id:"distribution", label:"5. Batch Distribution Compliance", icon:"◫",
    desc:"Validate that the batch meets the SOP-mandated distribution requirements before submission.",
    checks:[
      { id:"d1", severity:"critical", text:"All four data types are represented: single_turn, multi_turn, agentic, general_text.", guidance:"A batch missing any of the four data types is incomplete per Section 12 pilot requirements." },
      { id:"d2", severity:"critical", text:"All four attack categories are represented: jailbreak, prompt_injection, prompt_leakage, benign.", guidance:"Zero samples in any category = batch fails distribution requirement." },
      { id:"d3", severity:"major",    text:"Long-context coverage: at least some samples are >20K chars, and at least 10% of the batch is >10K chars.", guidance:"Per Section 12, long-context data must be represented in the pilot." },
      { id:"d4", severity:"major",    text:"Verified data is at least 25% of the batch (per Section 13 target ratio).", guidance:"Compute: count(verified=true) / total. If below 25%, flag as distribution gap." },
      { id:"d5", severity:"major",    text:"No single domain exceeds 15% of total samples (per Section 9).", guidance:"Compute per-domain counts. A domain at 16%+ is a distribution violation." },
      { id:"d6", severity:"minor",    text:"Role distribution is roughly within the target ranges from Section 8: user ~30%, system ~20%, assistant ~20%, tool ~10%, memory ~10%, env_feedback ~10%.", guidance:"Allow ±10pp deviation. Extreme imbalance (e.g., 80% user role) is a structural gap." },
      { id:"d7", severity:"minor",    text:"Data structure distribution is approximately 70% general_text and 30% structured formats.", guidance:"Flag if structured formats are <15% or >50% of batch." },
      { id:"d8", severity:"minor",    text:"Benign data covers all three tiers: Easy (~30%), Moderate (~40%), Hard (~30%). Tier is documented in source_description.", guidance:"If tier breakdown is not logged in source_description, ask annotators to add it before submission." },
      { id:"d9", severity:"major",    text:"Data length distribution includes samples across at least 6 of the 11 length buckets.", guidance:"A batch concentrated in 1–3 buckets fails the length diversity requirement." },
    ] },
  { id:"iaa", label:"6. Inter-Annotator Agreement", icon:"◌",
    desc:"Review IAA statistics and flag calibration issues before sign-off.",
    checks:[
      { id:"i1", severity:"critical", text:"README deliverable includes IAA statistics (Cohen's Kappa or Fleiss' Kappa) for overall label, severity, and intention separately.", guidance:"If README is missing IAA, hold batch until it is provided — it is a required deliverable per Section 16." },
      { id:"i2", severity:"major",    text:"Overall label IAA (jailbreak/injection/leakage/benign) is ≥ 0.70 (acceptable) or ≥ 0.80 (good). Flag if <0.70.", guidance:"<0.70 indicates annotators are disagreeing significantly on what constitutes an attack; escalate for calibration session." },
      { id:"i3", severity:"major",    text:"Severity score IAA (weighted Kappa or correlation) is ≥ 0.60. Severity is inherently harder to agree on than labels.", guidance:"Severity IAA <0.50 is a red flag — convene annotator calibration with worked examples from Appendix C." },
      { id:"i4", severity:"major",    text:"Intention label IAA is ≥ 0.65. 'Hard to say' should not be used by annotators to avoid judgment — check that 'hard_to_say' rate is <20% of all samples.", guidance:">20% hard_to_say suggests annotators are avoiding difficult calls. Facilitate a calibration review." },
      { id:"i5", severity:"major",    text:"Annotation was done independently — no evidence of cross-copying (e.g., identical annotation rationale strings across multiple annotators).", guidance:"Spot-check source_description or any rationale fields for near-duplicate text across different annotators." },
    ] },
  { id:"delivery", label:"7. Delivery Package", icon:"◻",
    desc:"Confirm all required deliverables are present and meet spec before submission to client.",
    checks:[
      { id:"dv1", severity:"critical", text:"Four JSONL files delivered: single_turn.jsonl, multi_turn.jsonl, agentic_turn.jsonl, general_text.jsonl.", guidance:"Missing any file = incomplete delivery. Empty files also count as missing." },
      { id:"dv2", severity:"major",    text:"File naming follows the SOP convention: {data_type}_{batch_number}_{date}.jsonl (e.g., single_turn_batch01_20260801.jsonl).", guidance:"Reject non-conforming filenames — they affect the client's ingestion pipeline." },
      { id:"dv3", severity:"critical", text:"README is present and includes: per-category counts, data type counts, structure format counts, length bucket counts, domain breakdown, role breakdown, severity distribution, verified vs. unverified breakdown, and IAA statistics.", guidance:"Check each section of the README against the checklist in Section 16. Missing subsections = incomplete." },
      { id:"dv4", severity:"major",    text:"All JSONL files are UTF-8 encoded with no BOM. Line endings are Unix (LF), not Windows (CRLF).", guidance:"Use file --mime-encoding and check for \\r characters. CRLF causes parse errors in some pipelines." },
      { id:"dv5", severity:"major",    text:"README distribution numbers match the actual file contents (cross-validate by counting).", guidance:"README stating 500 samples but file containing 487 is a discrepancy that must be resolved before delivery." },
      { id:"dv6", severity:"critical", text:"Batch has been validated against all Section 16 automated checks: no empty inputs, severity in range, label-severity consistency, char count accuracy, no intra-batch duplicates.", guidance:"Run the validation script before QE sign-off. Attach the validation report to the delivery package." },
    ] },
];
